### ISSUE TITLE
Jakarta-ize the Platform and WebProfile Specifications

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#38]
We need to update the Platform and WebProfile Specs to move away from "Java EE" and migrate to "Jakarta EE".  I originally documented the request via the platform-dev mailing list:

https://www.eclipse.org/lists/jakartaee-platform-dev/msg00531.html

We'll use this Issue to track the overall progress.  Due to the constrained timeline of this effort, we're not going to create separate issues for each chapter.  Just comment on this issue if you have plans to do a particular chapter.  But, in the end, actual PRs will win over intent.

Reference this post for the list of available chapters:
https://www.eclipse.org/lists/jakartaee-platform-dev/msg00532.html

Thanks for your help!

 To make it easy to track the progress
 - [x] specification/src/main/asciidoc/license-efsl.adoc
 - [x] specification/src/main/asciidoc/Platform-spec.adoc
 - [x] specification/src/main/asciidoc/WebProfile-spec.adoc
 - [x] specification/src/main/asciidoc/platform/Platform.adoc
 - [x] specification/src/main/asciidoc/platform/Profiles.adoc #44 
 - [x] specification/src/main/asciidoc/platform/ApplicationClients.adoc #79 
 - [x] specification/src/main/asciidoc/platform/Security.adoc #36 
 - [x] specification/src/main/asciidoc/platform/Introduction.adoc #43 
 - [x] specification/src/main/asciidoc/webprofile/WebProfile.adoc
 - [x] specification/src/main/asciidoc/webprofile/Introduction.adoc #54 
 - [x] specification/src/main/asciidoc/platform/RevisionHistory.adoc #58
 - [x] specification/src/main/asciidoc/platform/FutureDirections.adoc #41 
 - [x] specification/src/main/asciidoc/platform/Interoperability.adoc #42
 - [x] specification/src/main/asciidoc/platform/PlatformOverview.adoc #53
 - [x] specification/src/main/asciidoc/platform/RelatedDocuments.adoc #63
 - [x] specification/src/main/asciidoc/webprofile/RevisionHistory.adoc #58
 - [x] specification/src/main/asciidoc/webprofile/RelatedDocuments.adoc #63 
 - [x] specification/src/main/asciidoc/platform/TransactionManagement.adoc #50
 - [x] specification/src/main/asciidoc/platform/CompatibilityMigration.adoc #40 
 - [x] specification/src/main/asciidoc/webprofile/WebProfileDefinition.adoc #37
 - [x] specification/src/main/asciidoc/platform/ResourcesNamingInjection.adoc #46 (partial) and #82
 - [x] specification/src/main/asciidoc/platform/ApplicationProgrammingInterface.adoc #69 
 - [x] specification/src/main/asciidoc/platform/ServiceProviderInterface.adoc #47 
 - [x] specification/src/main/asciidoc/platform/ApplicationAssemblyDeployment.adoc  #39 
 - [x] specification/src/main/asciidoc/platform/PreviousVersionDeploymentDescriptors.adoc #65
 - [x] README.adoc

**Comment by kwsutter** [comment]
Scott Stark has taken the platform/Security chapter.

**Comment by kwsutter** [comment]
@kazumura has taken the webprofile/WebProfileDefinition chapter.  Thanks!

**Comment by Emily-Jiang** [comment]
Emily has taken platform/ApplicationAssemblyDeployment chapter

**Comment by smillidge** [comment]
Steve has taken platform/CompatibilityMigration.adoc

**Comment by kazumura** [comment]
Kenjj has taken  the section "Full Java EE Product Requirements" in "platform/Profiles.adoc".
https://github.com/eclipse-ee4j/jakartaee-platform/pull/44

**Comment by ganapathi004** [comment]
Ganapathi has taken platform/ResourcesNamingInjection.adoc

**Comment by xstefank** [comment]
Martin has taken platform/ServiceProviderInterface.adoc

**Comment by b6arat6** [comment]
Bharath has taken platform/TransactionManagement.adoc. PR is https://github.com/eclipse-ee4j/jakartaee-platform/pull/49

**Comment by ggam** [comment]
Guillermo takes platform/PlatformOverview.adoc (PR coming soon)

**Comment by sendilkumarn** [comment]
Taken specification/src/main/asciidoc/webprofile/Introduction.adoc  #54

**Comment by sendilkumarn** [comment]
To make it easy to track the progress
 - [ ] specification/src/main/asciidoc/license-efsl.adoc
 - [ ] specification/src/main/asciidoc/Platform-spec.adoc
 - [ ] specification/src/main/asciidoc/WebProfile-spec.adoc
 - [ ] specification/src/main/asciidoc/platform/Platform.adoc
 - [x] specification/src/main/asciidoc/platform/Profiles.adoc #44 
 - [x] specification/src/main/asciidoc/platform/Security.adoc #36 
 - [x] specification/src/main/asciidoc/platform/Introduction.adoc #43 
 - [ ] specification/src/main/asciidoc/webprofile/WebProfile.adoc
 - [x] specification/src/main/asciidoc/webprofile/Introduction.adoc #54 
 - [ ] specification/src/main/asciidoc/platform/RevisionHistory.adoc
 - [x] specification/src/main/asciidoc/platform/FutureDirections.adoc #41 
 - [x] specification/src/main/asciidoc/platform/Interoperability.adoc #42
 - [x] specification/src/main/asciidoc/platform/PlatformOverview.adoc (Taken)
 - [ ] specification/src/main/asciidoc/platform/RelatedDocuments.adoc
 - [ ] specification/src/main/asciidoc/webprofile/RevisionHistory.adoc
 - [ ] specification/src/main/asciidoc/webprofile/RelatedDocuments.adoc
 - [x] specification/src/main/asciidoc/platform/TransactionManagement.adoc #49
 - [x] specification/src/main/asciidoc/platform/CompatibilityMigration.adoc #40 
 - [x] specification/src/main/asciidoc/webprofile/WebProfileDefinition.adoc #37
 - [x] specification/src/main/asciidoc/platform/ResourcesNamingInjection.adoc #46 
 - [x] specification/src/main/asciidoc/platform/ServiceProviderInterface.adoc #47 
 - [ ] specification/src/main/asciidoc/platform/ApplicationAssemblyDeployment.adoc
 - [ ] specification/src/main/asciidoc/platform/PreviousVersionDeploymentDescriptors.adoc
 - [ ] README.adoc

**Comment by ggam** [comment]
Great job @sendilkumarn! @kwsutter can the checklist be added to the issue description?

**Comment by smillidge** [comment]
@ggam I added the checklist to the issue description

**Comment by b6arat6** [comment]
@smillidge @kwsutter Please update the PR from #49 to #50 for specification/src/main/asciidoc/platform/TransactionManagement.adoc.

**Comment by aguibert** [comment]
I can cover these two:
```
 specification/src/main/asciidoc/platform/RelatedDocuments.adoc
 specification/src/main/asciidoc/webprofile/RelatedDocuments.adoc
```

**Comment by Emily-Jiang** [comment]
Taking specification/src/main/asciidoc/platform/PreviousVersionDeploymentDescriptors.adoc

**Comment by kwsutter** [comment]
Thanks to @jim-krueger for picking up the "missing" ApplicationProgrammingInterface section!  PR #69

**Comment by kwsutter** [comment]
Didn't mean to close this yesterday...  Still have some work to do here...

**Comment by kwsutter** [comment]
Still need some help with the following sections...

 - [ ] specification/src/main/asciidoc/platform/ApplicationClients.adoc
 - [ ] specification/src/main/asciidoc/platform/ResourcesNamingInjection.adoc #46 (partial)

ApplicationClients.adoc was another section that was "hidden" due to the original conversion to asciidoc.  ResourcesNamingInjection.adoc was partially done via #46, but it still needs some work due to acronym usage.  Could use some PRs to help with this final push.  Thanks!

**Comment by xstefank** [comment]
I will take specification/src/main/asciidoc/platform/ApplicationClients.adoc.

**Comment by NottyCode** [comment]
I've added PR #82 to fix ResourcesNamingInjection

**Comment by kwsutter** [comment]
Okay, I think we're finally done with this portion of the exercise.  Anything more will be done via separate Issues and PRs.  Thanks for all of the help!
